on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: render-examples

jobs:
  render-examples:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install TeX Live packages
        run: sudo apt install -y texlive-base texlive-xetex latexmk

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          install.packages('pak')
          pak::pkg_install(c("rmarkdown", "MASS", "broom", "kableExtra"))
        shell: Rscript {0}

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: quarto-dev/quarto-actions/publish@v2
        with: 
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
          target: quarto-pub

